# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Katie Kowalsky
email: katelynekowalsky@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Katie Kowalsky is a cartographer, front-end web developer, and cheese enthusiast hailing from the great state of Wisconsin. Her passion for maps lends itself to talking, teaching, and even dancing about cartography.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://katiekowalsky.me" # the base hostname & protocol for your site
twitter_username: katiekowalsky
github_username:  kkowalsky


# Build settings
markdown: kramdown
